GET http://127.0.0.1:3001/api/notes

###

GET http://127.0.0.1:3001/api/notes/63e352e311c81f2823838b70

###

DELETE http://127.0.0.1:3001/api/notes/63e38c272c3f537bd6e12508

###

POST http://127.0.0.1:3001/api/notes
Content-Type: application/json

{
    "content": "VS Code REST Client is pretty good good good",
    "important": true
}

### 

PUT http://127.0.0.1:3001/api/notes/63e38c272c3f537bd6e12508
Content-Type: application/json

{
    "content": "VS1111",
    "important": false
}