GET http://127.0.0.1:3001/api/notes

###

GET http://127.0.0.1:3001/api/notes/63e35414bab1acf1113d24c2

###

DELETE http://127.0.0.1:3001/api/notes/63e35414bab1acf1113d24c2

###

POST http://127.0.0.1:3001/api/notes
Content-Type: application/json

{
    "content": "VS Code REST Client is pretty good",
    "important": true
}

### 

PUT http://127.0.0.1:3001/api/notes/63e35414bab1acf1113d24c2
Content-Type: application/json

{
    "content": "VS Code REST Client is very pretty good",
    "important": false
}